const DATA = [
  {
    nr: "01",
    id: "tour1",
    type: 'hike',
    island: 'LAP',
    title: "Camping along coast",
    bookmarkImgUrl: "bookmark01.jpg",
    cardLarge: "ok",
    cardLargeImgUrl400: ["tour1Ax1400.jpg", "tour1x1400.jpg", "tour1Cx1400.jpg"],
    cardLargeImgUr800: ["tour1Ax800.jpg", "tour1x800.jpg", "tour1Cx800.jpg"],
    cardLargeDescription: "7-day tour with the group up to 12 people and 2 tour guides. Sleeping in tents",
    cardDifficultyImageUrl: "dif01.png",
    cardSmallImgUrl: [],
    cardSmallName: "La Palma, Canaries",
    cardSmallDays: "7-day trip",
    cardOpinionNum: "",
    imageMain1400: "tour1x1400.jpg",
    imageMain800: "tour1x800.jpg",
    imageMain500: "tour1x500.jpg",
    days: "7 days",
    starPoints: 4.9,
    starOpinions: 78,
    startAndEndPoint: "Santa Cruz de La Palma",
    stops: ["1 city", "4 beaches"],
    stopPoints: ["Cala Martín Luís", "Puerto Trigo" ,"Playa de Nogales ","Cascada De Los Tilos"], 
    keywords: ["camping", "la palma", "hiking", "fully guided"],
    maxGroupSize: 18,
    minGroupSize: 12,
    sleeping: "tents",
    languages: "English, Spanish",
    food: "included",
    price: "€249",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ad unde porro neque natus recusandae assumenda iste sequi temporibus corrupti praesentium commodi, totam laborum libero facilis adipisci deleniti dolore ea ducimus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati doloremque quisquam nesciunt deleniti totam debitis, blanditiis eius. Omnis suscipit, laborum, aspernatur nam autem ducimus quae tempora enim ipsum ipsam quo!",
    descriptionCheckPoints: ["great fun", "4 stops", "water safety stuff", "2 leaders", "tents", "2 lifeguards", "all meals included", "insurance"],
    reviews: [
      {
        imageUrlJPG: "01tour1.jpg",
        imageUrlWEBP: "01tour1.webp",
        description: "One of the best time in my life.",
        name: "Dave",
      },
      {
        imageUrlJPG: "01tour2.jpg",
        imageUrlWEBO: "01tour2.webp",
        description: "Can't wait to join you also next year! With my people!.",
        name: "Ola",
      },
      {
        imageUrlJPG: "01tour3.jpg",
        imageUrlWEBO: "01tour3.webp",
        description: "This adventure gave me a lot of happines! I am coming back this next year also!",
        name: "Tom",
      },
      {
        imageUrlJPG: "01tour4.jpg",
        imageUrlWEBO: "01tour4.webp",
        description: "The morning hike is great!",
        name: "Eva",
      },
      {
        imageUrlJPG: "01tour5.jpg",
        imageUrlWEBO: "01tour5.webp",
        description: "Coming back every year! See you soon!",
        name: "Justin",
      },
      {
        imageUrlJPG: "01tour6.jpg",
        imageUrlWEBO: "01tour6.webp",
        description: "This views!",
        name: "Alexander",
      }
    ],
    comments: [
      {
        imageUser: "u1.jpg",
        name: "Amanda",
        comment: "one of the best adventures in my life"
      },
      {
        imageUser: "u4.jpg",
        name: "Frank",
        comment: "Mornings on the beach, hike, the views! Just amaizing!"
      }
    ]
  },
  {
    nr: "02",
    id:"tour2",
    type: 'waterSport',
    island: 'FUE',
    title: "Sailing around Canariest",
    bookmarkImgUrl: "bookmark02.jpg",
    cardLarge: "ok",
    cardLargeImgUrl400: ["tour2x1400.jpg", "tour2Bx1400.jpg", "tour2Cx1400.jpg"],
    cardLargeImgUr800: ["tour2x800.jpg", "tour2Bx800.jpg", "tour2Cx800.jpg"],
    cardLargeDescription: "5-day tour with the group up to 6 people and sailor. Sleeping on the sailboat",
    cardDifficultyImageUrl: "dif02.png",
    cardSmallImgUrl: [],
    cardSmallName: "Fuerteventura",
    cardSmallDays: "5-day trip",
    cardOpinionNum: "",
    imageMain1400: "tour2x1400.jpg",
    imageMain800: "tour2x800.jpg",
    imageMain500: "tour2x500.jpg",
    days: "5 days",
    starPoints: "4.8",
    starOpinions: 97,
    startAndEndPoint: "Puerto del Rosario",
    stops: ["3 harborns", "4 beaches"],
    stopPoints: ["Lobos", "Playa Flamingo", "Las Caletas", "Orzola", "La Graciosa", "Famara", "Playa de Cofete"], 
    keywords: ["sailing", "sea", "beach", "fully guided"],
    maxGroupSize: 18,
    minGroupSize: 8,
    sleeping: "sailboat",
    languages: "English, Spanish",
    food: "included",
    price: "€329",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ad unde porro neque natus recusandae assumenda iste sequi temporibus corrupti praesentium commodi, totam laborum libero facilis adipisci deleniti dolore ea ducimus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati doloremque quisquam nesciunt deleniti totam debitis, blanditiis eius. Omnis suscipit, laborum, aspernatur nam autem ducimus quae tempora enim ipsum ipsam quo!",
    descriptionCheckPoints: ["great fun", "7 stops", "water safety stuff", "2 leaders", "adventure", "2 lifeguards", "all meals included", "insurance"],
    reviews: [
      {
        imageUrlJPG: "02tour1.jpg",
        imageUrlWEBO: "02tour1.webp",
        description: "Great chill and relax time.",
        name: "Victor",
      },
      {
        imageUrlJPG: "02tour2.jpg",
        imageUrlWEBO: "02tour2.webp",
        description: "The trips to the wild beaches are the most incredible.",
        name: "Michael",
      },
      {
        imageUrlJPG: "02tour3.jpg",
        imageUrlWEBO: "02tour3.webp",
        description: "I bacome a sailor! Thanks for the lessons to the best guides!",
        name: "Misia",
      },
      {
        imageUrlJPG: "02tour4.jpg",
        imageUrlWEBO: "02tour4.webp",
        description: "This is life!",
        name: "Roger",
      },
      {
        imageUrlJPG: "02tour5.jpg",
        imageUrlWEBO: "02tour5.webp",
        description: "Sunset time on boat!",
        name: "Max",
      },
      {
        imageUrlJPG: "02tour6.jpg",
        imageUrlWEBO: "02tour6.webp",
        description: "Yeaaaahhh!",
        name: "Jasmine",
      }
    ],
    comments: [
      {
        imageUser: "u10.jpg",
        name: "Karo",
        comment: "That was a great time! See you this summer"
      }
    ] 
  }, 
  {
    nr: "03",
    id: "tour3",
    type: 'waterSport',
    island: 'TEN',
    title: "Surfing tour by van",
    bookmarkImgUrl: "bookmark03.jpg",
    cardLarge: "ok",
    cardLargeImgUrl400: ["tour3x1400.jpg", "tour3Bx1400.jpg", "tour3Cx1400.jpg"],
    cardLargeImgUr800: ["tour3x800.jpg", "tour3Bx800.jpg", "tour3Cx800.jpg"],
    cardLargeDescription: "10-day tour with the group up to 15 people and 4 tour guides. Sleeping in vans",
    cardDifficultyImageUrl: "dif03.png",
    cardSmallImgUrl: [],
    cardSmallName: "Tenerife, Canaries",
    cardSmallDays: "10-day trip",
    cardOpinionNum: "",
    imageMain1400: "tour3x1400.jpg",
    imageMain800: "tour3x800.jpg",
    imageMain500: "tour3x500.jpg",
    days: "10 days",
    starPoints: "5.0",
    starOpinions: 98,
    startAndEndPoint: "Santa Cruz de Tenerife",
    stops: ["6 beaches"],
    stopPoints: ["Playa de Las Gaviotas", "Playa de Roque Bermejo", "Playa Las Breñas", "Playa de Benijo", "Almáciga Beach", "Playa del Tamadite"], 
    keywords: ["camping", "tenerife", "surfing", "fully guided"],
    maxGroupSize: 18,
    minGroupSize: 10,
    sleeping: "vans",
    languages: "English, Spanish",
    food: "included",
    price: "€319",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ad unde porro neque natus recusandae assumenda iste sequi temporibus corrupti praesentium commodi, totam laborum libero facilis adipisci deleniti dolore ea ducimus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati doloremque quisquam nesciunt deleniti totam debitis, blanditiis eius. Omnis suscipit, laborum, aspernatur nam autem ducimus quae tempora enim ipsum ipsam quo!",
    descriptionCheckPoints: ["great fun", "3 drivers", "water safety stuff", "2 leaders", "vans", "3 lifeguards", "all meals included", "insurance"],
    reviews: [
      {
        imageUrlJPG: "03tour1.jpg",
        imageUrlWEBP: "03tour1.webp",
        description: "Surfing time! Sunset! This is a magic moment! Thanks to everyone!",
        name: "Amanda",
      },
      {
        imageUrlJPG: "03tour2.jpg",
        imageUrlWEBO: "03tour2.webp",
        description: "See ya!",
        name: "Jane",
      },
      {
        imageUrlJPG: "03tour3.jpg",
        imageUrlWEBO: "03tour3.webp",
        description: "Hey guys! I had great time with you!",
        name: "Angie",
      },
      {
        imageUrlJPG: "03tour4.jpg",
        imageUrlWEBO: "03tour4.webp",
        description: "Hey hi hello! Let's go",
        name: "Petra",
      },
      {
        imageUrlJPG: "03tour5.jpg",
        imageUrlWEBO: "03tour5.webp",
        description: "The best place in the world! Just love!",
        name: "Ali",
      },
      {
        imageUrlJPG: "03tour6.jpg",
        imageUrlWEBO: "03tour6.webp",
        description: "This vans!",
        name: "Zora",
      },
    ],
    comments: [
      {
        imageUser: "u5.jpg",
        name: "Patick",
        comment: "Surfing with sunsets!"
      },
      {
        imageUser: "u4.jpg",
        name: "Justin",
        comment: "The most beautiful place! Tenerife!"
      }
    ] ,
  },
  {
    nr: "04",
    id: "tour4",
    type: 'dayTrip',
    island: 'LAN',
    title: "La Graciosa by bike",
    bookmarkImgUrl: "bookmark04.jpg",
    cardSmall: "ok",
    cardLargeImgUrl400: ["tour4Ax1400.jpg", "tour4Bx1400.jpg", "tour4Cx1400.jpg"],
    cardLargeImgUr800: ["tour4Ax800.jpg", "tour4Bx800.jpg", "tour4Cx800.jpg"],
    cardLargeDescription: "",
    cardDifficultyImageUrl: "",
    cardSmallImgUrl: [],
    cardSmallName: "Lanzarote, Canaries",
    cardSmallDays: "1-day trip",
    cardOpinionNum: "",
    imageMain1400: "tour4x1400.jpg",
    imageMain800: "tour4x800.jpg",
    imageMain500: "tour4x500.jpg",
    days: "1 day",
    starPoints: 4.9,
    starOpinions: 99,
    startAndEndPoint: "Órzola, Lanzarote",
    stops: ["2 viewpoints", "4 beaches"],
    stopPoints: ["Caleta del Sebo", "Barranco de los Conejos", "Playa Lambra", "Playa de las Conchas", "Playa de la Cocina", "Playa Francesa"], 
    keywords: ["bike", "isla", "archipelago", "fully guided"],
    maxGroupSize: 18,
    minGroupSize: 15,
    sleeping: "-",
    languages: "English, Spanish",
    food: "included",
    price: "€79",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ad unde porro neque natus recusandae assumenda iste sequi temporibus corrupti praesentium commodi, totam laborum libero facilis adipisci deleniti dolore ea ducimus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati doloremque quisquam nesciunt deleniti totam debitis, blanditiis eius. Omnis suscipit, laborum, aspernatur nam autem ducimus quae tempora enim ipsum ipsam quo!",
    descriptionCheckPoints: ["great fun", "4 stops", "water safety stuff", "2 leaders", "bicycles", "2 lifeguards", "all meals included", "insurance"],
    reviews: [
      {
        imageUrlJPG: "04tour1.jpg",
        imageUrlWEBP: "04tour1.webp",
        description: "Just Woooow wooow woooow! Perfect day trip!",
        name: "Ash",
      },
      {
        imageUrlJPG: "04tour2.jpg",
        imageUrlWEBO: "04tour2.webp",
        description: "We had so much fun!",
        name: "Klark",
      },
      {
        imageUrlJPG: "04tour3.jpg",
        imageUrlWEBO: "04tour3.webp",
        description: "Super hot weather!",
        name: "Marco",
      },
      {
        imageUrlJPG: "04tour4.jpg",
        imageUrlWEBO: "04tour4.webp",
        description: "Let's do this again!",
        name: "Emie",
      },
      {
        imageUrlJPG: "04tour5.jpg",
        imageUrlWEBO: "04tour5.webp",
        description: "One of the most beautiful day!!!!",
        name: "Michia",
      },
      {
        imageUrlJPG: "04tour6.jpg",
        imageUrlWEBO: "04tour6.webp",
        description: "Just incredible!",
        name: "Nicola",
      },
    ],
    comments: [
      {
        imageUser: "u1.jpg",
        name: "Amanda",
        comment: "Worth it!"
      },
    ] ,
  },
  {
    nr: "05",
    id: "tour5",
    type: 'waterSport',
    island: 'LAG',
    title: "Sailing with Gigantes",
    bookmarkImgUrl: "bookmark05.jpg",
    cardSmall: "ok",
    cardLargeImgUrl400: ["tour5Ax1400.jpg", "tour5Bx1400.jpg", "tour5Cx1400.jpg"],
    cardLargeImgUr800: ["tour5Ax800.jpg", "tour5Bx800.jpg", "tour5Cx800.jpg"],
    cardLargeDescription: "",
    cardDifficultyImageUrl: "",
    cardSmallImgUrl: [],
    cardSmallName: "La Gomera, Canaries",
    cardSmallDays: "5-day trip",
    cardOpinionNum: "",
    imageMain1400: "tour5x1400.jpg",
    imageMain800: "tour5x800.jpg",
    imageMain500: "tour5x500.jpg",
    days: "5 days",
    starPoints: 4.7,
    starOpinions: 57,
    startAndEndPoint: "Los Gigantes,Tenerife",
    stops: ["2 cities", "5 beaches"],
    stopPoints: ["Playa Barranco Seco", "San Sebastián de la Gomera", "Playa de Ávalo", "Punta de los Órganos", "Playa de Heredia", "Playa del Inglés"], 
    keywords: ["sailing", "tenerife", "la gomera", "fully guided"],
    maxGroupSize: 18,
    minGroupSize: 10,
    sleeping: "sailboat",
    languages: "English, Spanish",
    food: "included",
    price: "€239",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ad unde porro neque natus recusandae assumenda iste sequi temporibus corrupti praesentium commodi, totam laborum libero facilis adipisci deleniti dolore ea ducimus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati doloremque quisquam nesciunt deleniti totam debitis, blanditiis eius. Omnis suscipit, laborum, aspernatur nam autem ducimus quae tempora enim ipsum ipsam quo!",
    descriptionCheckPoints: ["great fun", "6 stops", "water safety stuff", "2 leaders", "sailboat", "2 lifeguards", "all meals included", "insurance"],
    reviews: [
      {
        imageUrlJPG: "05tour1.jpg",
        imageUrlWEBP: "05tour1.webp",
        description: "Sailors on board!",
        name: "Davide",
      },
      {
        imageUrlJPG: "05tour2.jpg",
        imageUrlWEBO: "05tour2.webp",
        description: "The best adventure! So clean water!",
        name: "Karo",
      },
      {
        imageUrlJPG: "05tour3.jpg",
        imageUrlWEBO: "05tour3.webp",
        description: "Kayaking to the beaches! What a great time",
        name: "Fran",
      },
      {
        imageUrlJPG: "05tour4.jpg",
        imageUrlWEBO: "05tour4.webp",
        description: "It's all starts here!",
        name: "Robert",
      },
      {
        imageUrlJPG: "05tour5.jpg",
        imageUrlWEBO: "05tour5.webp",
        description: "Like this we spent all days! Just woow! Definitely for a sailing lovers!",
        name: "Mona",
      },
      {
        imageUrlJPG: "05tour6.jpg",
        imageUrlWEBO: "05tour6.webp",
        description: "Cool! A lot of beaches to see!",
        name: "Adam",
      },
    ],
    comments: [
      {
        imageUser: "u5.jpg",
        name: "Patric",
        comment: "The best adventures! So much fun!"
      },
    ] ,
  },
  {
    nr: "06",
    id: "tour6",
    type: 'dayTrip',
    title: "Discovering Lobos",
    island: 'FUE',
    bookmarkImgUrl: "bookmark06.jpg",
    cardSmall: "ok",
    cardLargeImgUrl400: ["tour6Ax1400.jpg", "tour6Bx1400.jpg", "tour6Cx1400.jpg"],
    cardLargeImgUr800: ["tour6Ax800.jpg", "tour6Bx800.jpg", "tour6Cx800.jpg"],
    cardLargeDescription: "",
    cardDifficultyImageUrl: "",
    cardSmallImgUrl: [],
    cardSmallName: "Fuerteventura",
    cardSmallDays: "1-day trip",
    cardOpinionNum: "",
    imageMain1400: "tour6x1400.jpg",
    imageMain800: "tour6x800.jpg",
    imageMain500: "tour6x500.jpg",
    days: "1 day",
    starPoints: 4.7,
    starOpinions: 43,
    startAndEndPoint: " Puerto de Corralejo",
    stops: ["1 city", "4 beaches"],
    stopPoints: ["El Puertito", "Las Lagunitas", "Punta Martiño lighthouse", "Montaña La Caldera"], 
    keywords: ["beach", "lobos", "relax", "fully guided"],
    maxGroupSize: 18,
    minGroupSize: 12,
    sleeping: "-",
    languages: "English, Spanish",
    food: "included",
    price: "€129",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ad unde porro neque natus recusandae assumenda iste sequi temporibus corrupti praesentium commodi, totam laborum libero facilis adipisci deleniti dolore ea ducimus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati doloremque quisquam nesciunt deleniti totam debitis, blanditiis eius. Omnis suscipit, laborum, aspernatur nam autem ducimus quae tempora enim ipsum ipsam quo!",
    descriptionCheckPoints: ["great fun", "4 stops", "water safety stuff", "2 leaders", "tents", "2 lifeguards", "all meals included", "insurance"],
    reviews: [
      {
        imageUrlJPG: "06tour1.jpg",
        imageUrlWEBP: "06tour1.webp",
        description: "Ready for the next year!",
        name: "Nick",
      },
      {
        imageUrlJPG: "06tour2.jpg",
        imageUrlWEBO: "06tour2.webp",
        description: "Can not wait to come back under the sea!.",
        name: "Cinii",
      },
      {
        imageUrlJPG: "06tour3.jpg",
        imageUrlWEBO: "06tour3.webp",
        description: "We had such a great time in Lobos!",
        name: "Olaf",
      },
      {
        imageUrlJPG: "06tour4.jpg",
        imageUrlWEBO: "06tour4.webp",
        description: "My team! See you soon!",
        name: "Julia",
      },
      {
        imageUrlJPG: "06tour5.jpg",
        imageUrlWEBO: "06tour5.webp",
        description: "You just have to come and swim!",
        name: "John",
      },
      {
        imageUrlJPG: "06tour6.jpg",
        imageUrlWEBO: "06tour6.webp",
        description: "Looking for a new freinds under the sea!!",
        name: "Eliot",
      },
    ],
    comments: [
      {
        imageUser: "u8.jpg",
        name: "Matalie",
        comment: "The islang is just amaizing!!"
      },
    ] ,
  },
  {
    nr: "07",
    id: "tour7",
    type: 'hike',
    island: 'TEN',
    title: "Anaga hike",
    bookmarkImgUrl: "bookmark07.jpg",
    cardSmall: "ok",
    cardLargeImgUrl400: ["tour7Ax1400.jpg", "tour7Bx1400.jpg", "tour7Cx1400.jpg"],
    cardLargeImgUr800: ["tour7Ax800.jpg", "tour7Bx800.jpg", "tour7Cx800.jpg"],
    cardLargeDescription: "",
    cardDifficultyImageUrl: "",
    cardSmallImgUrl: [],
    cardSmallName: "Tenerife, Canaries",
    cardSmallDays: "2-day trip",
    cardOpinionNum: "",
    imageMain1400: "tour7x1400.jpg",
    imageMain800: "tour7x800.jpg",
    imageMain500: "tour7x500.jpg",
    days: "2 days",
    starPoints: 4.8,
    starOpinions: 38,
    startAndEndPoint: "Santa Cruz de Tenerife",
    stops: ["1 city", "4 viewpoints"],
    stopPoints: ["La Laguna", "Las Lagunetas", "Las Cañadas del Teide", "Capilla de la Fortaleza", "Pico del Teide", "Boca Tauce"], 
    keywords: ["camping", "tenerife", "hiking", "fully guided"],
    maxGroupSize: 18,
    minGroupSize: 10,
    sleeping: "tents",
    languages: "English, Spanish",
    food: "included",
    price: "€69",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ad unde porro neque natus recusandae assumenda iste sequi temporibus corrupti praesentium commodi, totam laborum libero facilis adipisci deleniti dolore ea ducimus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati doloremque quisquam nesciunt deleniti totam debitis, blanditiis eius. Omnis suscipit, laborum, aspernatur nam autem ducimus quae tempora enim ipsum ipsam quo!",
    descriptionCheckPoints: ["great fun", "4 stops", "cars", "2 leaders", "tents", "2 lifeguards", "all meals included", "insurance"],
    reviews: [
      {
        imageUrlJPG: "07tour1.jpg",
        imageUrlWEBP: "07tour1.webp",
        description: "We are coming back soon",
        name: "Michael",
      },
      {
        imageUrlJPG: "07tour2.jpg",
        imageUrlWEBO: "0tour2.webp",
        description: "This forest!",
        name: "Ana",
      },
      {
        imageUrlJPG: "07tour3.jpg",
        imageUrlWEBO: "07tour3.webp",
        description: "This adventure gave me a lot of happines!",
        name: "Nicolas",
      },
      {
        imageUrlJPG: "07tour4.jpg",
        imageUrlWEBO: "07tour4.webp",
        description: "Magic!",
        name: "Abby",
      },
      {
        imageUrlJPG: "07tour5.jpg",
        imageUrlWEBO: "07tour5.webp",
        description: "Coming back every year! See you soon!",
        name: "Maggie",
      },
      {
        imageUrlJPG: "07tour6.jpg",
        imageUrlWEBO: "07tour6.webp",
        description: "Comming soon!",
        name: "Caylee",
      },
    ],
    comments: [
      {
        imageUser: "u11.jpg",
        name: "Adam",
        comment: "So much hike but amaizing views!"
      },
      {
        imageUser: "u3.jpg",
        name: "Justin",
        comment: "Haha yes I remember that! But was worth it! The best memories!"
      }
    ]
  },
  {
    nr: "08",
    id: "tour8",
    type: 'waterSport',
    island: 'GRA',
    title: "Dunas Maspalomas",
    bookmarkImgUrl: "bookmark08.jpg",
    cardMedium: "ok",
    cardLargeImgUrl400: ["tour8Ax1400.jpg", "tour8Bx1400.jpg", "tour8Cx1400.jpg"],
    cardLargeImgUr800: ["tour8Ax800.jpg", "tour8Bx800.jpg", "tour8Cx800.jpg"],
    cardLargeDescription: "",
    cardDifficultyImageUrl: "",
    cardSmallImgUrl: [],
    cardSmallName: "Gran Canaria",
    cardSmallDays: "1-day trip",
    cardOpinionNum: "154",
    imageMain1400: "tour8x1400.jpg",
    imageMain800: "tour8x800.jpg",
    imageMain500: "tour8x500.jpg",
    days: "1 day",
    starPoints: 4.8,
    starOpinions: 154,
    startAndEndPoint: "Maspalomas",
    stops: ["1 city", "dunas"],
    stopPoints: ["Dunes of Maspalomas", "Playa del Inglés"], 
    keywords: ["beach", "gran canaria", "walking", "fully guided"],
    maxGroupSize: 18,
    minGroupSize: 15,
    sleeping: "-",
    languages: "English, Spanish",
    food: "included",
    price: "€29",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ad unde porro neque natus recusandae assumenda iste sequi temporibus corrupti praesentium commodi, totam laborum libero facilis adipisci deleniti dolore ea ducimus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati doloremque quisquam nesciunt deleniti totam debitis, blanditiis eius. Omnis suscipit, laborum, aspernatur nam autem ducimus quae tempora enim ipsum ipsam quo!",
    descriptionCheckPoints: ["great fun", "dunas", "water safety stuff", "2 leaders", "sandboarding", "2 lifeguards", "all meals included", "insurance"],
    reviews: [
      {
        imageUrlJPG: "08tour1.jpg",
        imageUrlWEBP: "08tour1.webp",
        description: "Something unique!",
        name: "Em",
      },
      {
        imageUrlJPG: "08tour2.jpg",
        imageUrlWEBO: "08tour2.webp",
        description: "Yeeeaah it was so much fun! One day trip but with amaizing people!.",
        name: "Dominic",
      },
      {
        imageUrlJPG: "08tour3.jpg",
        imageUrlWEBO: "08tour3.webp",
        description: "This adventure gave me a lot of happines! I am coming back in this year too!",
        name: "Tom",
      },
      {
        imageUrlJPG: "08tour4.jpg",
        imageUrlWEBO: "08tour4.webp",
        description: "Beach time!",
        name: "Eva",
      },
      {
        imageUrlJPG: "08tour5.jpg",
        imageUrlWEBO: "08tour5.webp",
        description: "Coming back every year! See you soon!",
        name: "Julia",
      },
      {
        imageUrlJPG: "08tour6.jpg",
        imageUrlWEBO: "08tour6.webp",
        description: "This views!",
        name: "Alexander",
      },
    ],
    comments: [
      {
        imageUser: "u12.jpg",
        name: "Michaela",
        comment: "So cool! Amaizing activities and group!"
      },
    ] 
  },
  {
    nr: "09",
    id: "tour9",
    type: 'waterSport',
    title: "Benijo Surfing",
    island: 'TEN',
    bookmarkImgUrl: "bookmark09.jpg",
    cardMedium: "ok",
    cardLargeImgUrl400: ["tour9Ax1400.jpg", "tour9Bx1400.jpg", "tour9Cx1400.jpg"],
    cardLargeImgUr800: ["tour9Ax800.jpg", "tour9Bx800.jpg", "tour9Cx800.jpg"],
    cardLargeDescription: "",
    cardDifficultyImageUrl: "",
    cardSmallImgUrl: [],
    cardSmallName: "Tenerife, Canaries",
    cardSmallDays: "6-day trip",
    cardOpinionNum: "94",
    imageMain1400: "tour9x1400.jpg",
    imageMain800: "tour9x800.jpg",
    imageMain500: "tour9x500.jpg",
    days: "6 days",
    starPoints: 5.0,
    starOpinions: 94,
    startAndEndPoint: "Santa Cruz de Tenerife",
    stops: ["1 city", "4 beaches"],
    stopPoints: ["Playa de Las Gaviotas", "Playa de Benijo", "Almáciga Beach", "Playa del Tamadite"], 
    keywords: ["camping", "tenerife", "surfing", "fully guided"],
    maxGroupSize: 18,
    minGroupSize: 15,
    sleeping: "vans",
    languages: "English, Spanish",
    food: "included",
    price: "€149",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ad unde porro neque natus recusandae assumenda iste sequi temporibus corrupti praesentium commodi, totam laborum libero facilis adipisci deleniti dolore ea ducimus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati doloremque quisquam nesciunt deleniti totam debitis, blanditiis eius. Omnis suscipit, laborum, aspernatur nam autem ducimus quae tempora enim ipsum ipsam quo!",
    descriptionCheckPoints: ["great fun", "4 stops", "water safety stuff", "2 leaders", "vans", "2 lifeguards", "all meals included", "insurance"],
    reviews: [
      {
        imageUrlJPG: "09tour1.jpg",
        imageUrlWEBP: "09tour1.webp",
        description: "One of the best time in my life! The most beautiful beach!!!",
        name: "Ola",
      },
      {
        imageUrlJPG: "09tour2.jpg",
        imageUrlWEBO: "09tour2.webp",
        description: "Good waves!",
        name: "Lauren",
      },
      {
        imageUrlJPG: "09tour3.jpg",
        imageUrlWEBO: "09tour3.webp",
        description: "Surfing group of people! Miss this time!",
        name: "Vanessa",
      },
      {
        imageUrlJPG: "09tour4.jpg",
        imageUrlWEBO: "09tour4.webp",
        description: "The color! We did it!",
        name: "Camelia",
      },
      {
        imageUrlJPG: "09tour5.jpg",
        imageUrlWEBO: "09tour5.webp",
        description: "Excited for the next year! See you soon!",
        name: "Kora",
      },
      {
        imageUrlJPG: "09tour6.jpg",
        imageUrlWEBO: "09tour6.webp",
        description: "This is fun!!!",
        name: "Chris",
      },
    ],
    comments: [
      {
        imageUser: "u6.jpg",
        name: "Paul",
        comment: "Benijo is a place You must see!!"
      },
      {
        imageUser: "u2.jpg",
        name: "Tom",
        comment: "Top 1!"
      },
    ] 
  },
  {
    nr: "10",
    id: "tour10",
    type: 'hike',
    island: 'TEN',
    title: "Volcano el Teide",
    bookmarkImgUrl: "bookmark10.jpg",
    cardMedium: "ok",
    cardLargeImgUrl400: ["tour10Ax1400.jpg", "tour10Bx1400.jpg", "tour10Cx1400.jpg"],
    cardLargeImgUr800: ["tour10Ax800.jpg", "tour10Bx800.jpg", "tour10Cx800.jpg"],
    cardLargeDescription: "",
    cardDifficultyImageUrl: "",
    cardSmallImgUrl: [],
    cardSmallName: "Tenerife, Canaries",
    cardSmallDays: "3-day trip",
    cardOpinionNum: "114",
    imageMain1400: "tour10x1400.jpg",
    imageMain800: "tour10x800.jpg",
    imageMain500: "tour10x500.jpg",
    days: "3 days",
    starPoints: 4.9,
    starOpinions: 114,
    startAndEndPoint: "Santa Cruz de Tenerife",
    stops: ["1 city", "4 viewpoints"],
    stopPoints: ["Santa Cruz De Tenerife", "La Laguna", "La Esperanza", "Mirador de Chipeque", "Mirador de La Crucita", "Teide"], 
    keywords: ["camping", "tenerife", "hiking", "fully guided"],
    maxGroupSize: 18,
    minGroupSize: 12,
    sleeping: "tents",
    languages: "English, Spanish",
    food: "included",
    price: "€169",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ad unde porro neque natus recusandae assumenda iste sequi temporibus corrupti praesentium commodi, totam laborum libero facilis adipisci deleniti dolore ea ducimus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati doloremque quisquam nesciunt deleniti totam debitis, blanditiis eius. Omnis suscipit, laborum, aspernatur nam autem ducimus quae tempora enim ipsum ipsam quo!",
    descriptionCheckPoints: ["great fun", "4 stops", "water safety stuff", "2 leaders", "tents", "camping equipment", "all meals included", "insurance"],
    reviews: [
      {
        imageUrlJPG: "10tour1.jpg",
        imageUrlWEBP: "10tour1.webp",
        description: "One of the best time in my life!",
        name: "Amie",
      },
      {
        imageUrlJPG: "10tour2.jpg",
        imageUrlWEBO: "10tour2.webp",
        description: "The most beautiful view in Tenerife",
        name: "Polly",
      },
      {
        imageUrlJPG: "10tour3.jpg",
        imageUrlWEBO: "10tour3.webp",
        description: "Peace!",
        name: "Ola",
      },
      {
        imageUrlJPG: "10tour4.jpg",
        imageUrlWEBO: "10tour4.webp",
        description: "The morning hike is great!",
        name: "Tom",
      },
      {
        imageUrlJPG: "10tour5.jpg",
        imageUrlWEBO: "10tour5.webp",
        description: "Yeahh here we are!",
        name: "Caramella",
      },
      {
        imageUrlJPG: "10tour6.jpg",
        imageUrlWEBO: "10tour6.webp",
        description: "Love it!",
        name: "Emily",
      },
    ],
    comments: [
      {
        imageUser: "u10.jpg",
        name: "Arina",
        comment: "Woow! So nice trip!"
      },
    ] 
  },
  {
    nr: "11",
    id: "tour11",
    type: 'waterSport',
    island: 'ELH',
    title: "Hop Diving",
    bookmarkImgUrl: "bookmark10.jpg",
    cardLargeImgUrl400: ["tour10Ax1400.jpg", "tour10Bx1400.jpg", "tour10Cx1400.jpg"],
    cardLargeImgUr800: ["tour10Ax800.jpg", "tour10Bx800.jpg", "tour10Cx800.jpg"],
    cardLargeDescription: "",
    cardDifficultyImageUrl: "",
    cardSmallImgUrl: [],
    cardSmallName: "El Hierro, Canaries",
    cardSmallDays: "4-day trip",
    cardOpinionNum: "",
    imageMain1400: "tour11x1400.jpg",
    imageMain800: "tour11x800.jpg",
    imageMain500: "tour11x500.jpg",
    days: "4 days",
    starPoints: 4.9,
    starOpinions: 44,
    startAndEndPoint: "La Restinga Puerto Deportivo",
    stops: ["4 beaches"],
    stopPoints: ["La Restinga Puerto Deportivo", "Playa de las Alcusas", "Playa de las Calcosas", "Charco Azul"], 
    keywords: ["diving", "el hierro", "boats", "fully guided"],
    maxGroupSize: 18,
    minGroupSize: 10,
    sleeping: "boats",
    languages: "English, Spanish",
    food: "included",
    price: "€319",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ad unde porro neque natus recusandae assumenda iste sequi temporibus corrupti praesentium commodi, totam laborum libero facilis adipisci deleniti dolore ea ducimus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati doloremque quisquam nesciunt deleniti totam debitis, blanditiis eius. Omnis suscipit, laborum, aspernatur nam autem ducimus quae tempora enim ipsum ipsam quo!",
    descriptionCheckPoints: ["great fun", "4 stops", "water safety stuff", "2 leaders", "boats", "2 lifeguards", "all meals included", "insurance"],
    reviews: [
      {
        imageUrlJPG: "11tour1.jpg",
        imageUrlWEBP: "11tour1.webp",
        description: "I tried once and I can not wait to be back!",
        name: "Dona",
      },
      {
        imageUrlJPG: "11tour2.jpg",
        imageUrlWEBO: "11tour2.webp",
        description: "No words! Something amaizing!",
        name: "Sara",
      },
      {
        imageUrlJPG: "11tour3.jpg",
        imageUrlWEBO: "11tour3.webp",
        description: "Soo coool!",
        name: "Caty",
      },
      {
        imageUrlJPG: "11tour4.jpg",
        imageUrlWEBO: "11tour4.webp",
        description: "So so so much fun!",
        name: "Marta",
      },
      {
        imageUrlJPG: "11tour5.jpg",
        imageUrlWEBO: "11tour5.webp",
        description: "Coming back this week!",
        name: "Jacob",
      },
      {
        imageUrlJPG: "11tour6.jpg",
        imageUrlWEBO: "11tour6.webp",
        description: "Miss this!!!",
        name: "Andrea",
      },
    ],
    comments: [
      {
        imageUser: "u12.jpg",
        name: "Michaela",
        comment: "Under the see! Take me back! See you this summer!"
      },
    ] 
  },
  {
    nr: "12",
    id: "tour12",
    type: 'waterSport',
    island: 'FUE',
    title: "Fast Wind",
    bookmarkImgUrl: "bookmark12.jpg",
    cardLargeImgUrl400: ["tour12Ax1400.jpg", "tour12Bx1400.jpg", "tour12Cx1400.jpg"],
    cardLargeImgUr800: ["tour12Ax800.jpg", "tour12Bx800.jpg", "tour12Cx800.jpg"],
    cardLargeDescription: "",
    cardDifficultyImageUrl: "",
    cardSmallImgUrl: [],
    cardSmallName: "Fuerteventura",
    cardSmallDays: "1-day trip",
    cardOpinionNum: "",
    imageMain1400: "tour12x1400.jpg",
    imageMain800: "tour12x800.jpg",
    imageMain500: "tour12x500.jpg",
    days: "1 day",
    starPoints: 4.9,
    starOpinions: 38,
    startAndEndPoint: "Playa Esmeralda",
    stops: ["2 beaches"],
    stopPoints: ["Playa Esmeralda", "Playa Esquinzo-Butihondom"], 
    keywords: ["windsurfing", "fuerte", "beach", "fully guided"],
    maxGroupSize: 18,
    minGroupSize: 15,
    sleeping: "-",
    languages: "English, Spanish",
    food: "included",
    price: "€49",
    description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Ad unde porro neque natus recusandae assumenda iste sequi temporibus corrupti praesentium commodi, totam laborum libero facilis adipisci deleniti dolore ea ducimus. Lorem ipsum dolor sit amet consectetur adipisicing elit. Obcaecati doloremque quisquam nesciunt deleniti totam debitis, blanditiis eius. Omnis suscipit, laborum, aspernatur nam autem ducimus quae tempora enim ipsum ipsam quo!",
    descriptionCheckPoints: ["great fun", "2 beaches", "water safety stuff", "2 leaders", "windsurfing equipment", "2 lifeguards", "all meals included", "insurance"],
    reviews: [
      {
        imageUrlJPG: "12tour1.jpg",
        imageUrlWEBP: "12tour1.webp",
        description: "My fav place!",
        name: "Caro",
      },
      {
        imageUrlJPG: "12tour2.jpg",
        imageUrlWEBO: "12tour2.webp",
        description: "The best wind!",
        name: "Gaby",
      },
      {
        imageUrlJPG: "12tour3.jpg",
        imageUrlWEBO: "12tour3.webp",
        description: "Yeeahhh! Sth what I love!",
        name: "Tom",
      },
      {
        imageUrlJPG: "12tour4.jpg",
        imageUrlWEBO: "12tour4.webp",
        description: "Let's do this again!",
        name: "Mike",
      },
      {
        imageUrlJPG: "12tour5.jpg",
        imageUrlWEBO: "12tour5.webp",
        description: "Chill and relax! Miss this sunsets!",
        name: "Emma",
      },
      {
        imageUrlJPG: "12tour6.jpg",
        imageUrlWEBO: "12tour6.webp",
        description: "So much fun!",
        name: "Alex",
      },
    ],
    comments: [
      {
        imageUser: "u9.jpg",
        name: "Karo",
        comment: "The best wind! So fast! Great adventure!"
      },
      {
        imageUser: "u13.jpg",
        name: "Fran",
        comment: "Amaizing! The colors! Woow!"
      },
      {
        imageUser: "u2.jpg",
        name: "Tom",
        comment: "See you this summer guys!!"
      },
    ] 
  }
]

export default DATA;